appuser_admin_frontend_user:
    type: rest
    resource: Savwy\SuluBundle\ApplicationUserBundle\Controller\Admin\FrontendUserController
appuser_admin_backend_user:
    type: rest
    resource: Savwy\SuluBundle\ApplicationUserBundle\Controller\Admin\BackendUserController
#appuser_admin_frontend_group:
#    type: rest
#    resource: Savwy\SuluBundle\ApplicationUserBundle\Controller\FrontendGroupController
#appuser_admin_backend_group:
#    type: rest
#    resource: Savwy\SuluBundle\ApplicationUserBundle\Controller\BackendGroupController
